all:
	echo "all:`date --rfc-3339=ns`" >> build.log

install:
	echo "install:`date --rfc-3339=ns`" >> build.log

build:
	echo "build:`date --rfc-3339=ns`" >> build.log

test:
	echo "test:`date --rfc-3339=ns`" >> build.log

